version: '3.9'
services:
  spring-boot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "docker-mysql:3306", "--", "sh", "run.sh"] # <-- look here!
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - docker-mysql
    links:
      - docker-mysql
    ports:
      - 8888:8080
    environment:
      -MYSQL_HOST: docker-mysql
  docker-mysql:
    image: mysql:latest
    ports:
      - 3333:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trex
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
