version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trex
    ports:
      - "3333:3306"
  myapp:
    build: .
    ports:
      - "8888:8080"
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 500
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
