version: "3.9"
services:
  db-server:
    image: mysql:5.7.35
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=trex
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
    ports:
      - "3333:3306"
  web:
    build: .
    ports:
      - "8080:8080"




